import type { AgentContext } from "./types.js";

export function generateInstructions(context: AgentContext): string {
  const lines: string[] = [];

  lines.push("# Dikta Project Instructions");
  lines.push("");
  lines.push("> Auto-generated by `dikta context`. Do not edit manually.");
  lines.push("");

  // Schema overview
  appendSchemaOverview(lines, context);

  // Relationships
  appendRelationships(lines, context);

  // PII fields
  appendPiiFields(lines, context);

  // State machines
  appendStateMachines(lines, context);

  // Contracts summary
  appendContractsSummary(lines, context);

  // Policies
  appendPolicies(lines, context);

  // Verification commands
  appendVerificationCommands(lines);

  return lines.join("\n");
}

function appendSchemaOverview(lines: string[], context: AgentContext): void {
  const { schema_summary } = context;
  lines.push("## Schema Overview");
  lines.push("");
  lines.push(`- **Entities**: ${schema_summary.entities.length}`);
  lines.push(`- **Names**: ${schema_summary.entities.join(", ")}`);
  lines.push(`- **Invariants**: ${schema_summary.invariants_count}`);
  lines.push("");
}

function appendRelationships(lines: string[], context: AgentContext): void {
  const { relationships } = context.schema_summary;
  if (relationships.length === 0) return;

  lines.push("## Relationships");
  lines.push("");
  lines.push("| From | To | Type |");
  lines.push("|------|----|------|");
  for (const rel of relationships) {
    lines.push(`| ${rel.from} | ${rel.to} | ${rel.type} |`);
  }
  lines.push("");
}

function appendPiiFields(lines: string[], context: AgentContext): void {
  const { pii_fields } = context.schema_summary;
  if (pii_fields.length === 0) return;

  lines.push("## PII Fields");
  lines.push("");
  lines.push("**DO NOT LOG** the following fields:");
  lines.push("");
  for (const field of pii_fields) {
    lines.push(`- \`${field}\``);
  }
  lines.push("");
}

function appendStateMachines(lines: string[], context: AgentContext): void {
  const { state_machines } = context.schema_summary;
  if (state_machines.length === 0) return;

  lines.push("## State Machines");
  lines.push("");
  for (const sm of state_machines) {
    lines.push(`- \`${sm}\``);
  }
  lines.push("");
}

function appendContractsSummary(lines: string[], context: AgentContext): void {
  const { contracts_summary } = context;
  lines.push("## Query Contracts");
  lines.push("");
  lines.push(`- **Total**: ${contracts_summary.total}`);

  const byEntity = Object.entries(contracts_summary.by_entity);
  if (byEntity.length > 0) {
    lines.push("- **By entity**:");
    for (const [entity, count] of byEntity) {
      lines.push(`  - ${entity}: ${count}`);
    }
  }

  const budgets = contracts_summary.performance_budgets;
  if (budgets.index_only_count > 0) {
    lines.push(`- **Index-only queries**: ${budgets.index_only_count}`);
  }
  if (budgets.capped_queries.length > 0) {
    lines.push("- **Capped queries**:");
    for (const cq of budgets.capped_queries) {
      lines.push(`  - ${cq.query}: max ${cq.max_rows} rows`);
    }
  }
  lines.push("");
}

function appendPolicies(lines: string[], context: AgentContext): void {
  lines.push("## Policies");
  lines.push("");

  const { policies } = context;
  if (policies.tenant_isolation) {
    lines.push("- **Tenant isolation**: All queries MUST include row_filter in WHERE clause");
  }
  if (policies.pii_logging) {
    lines.push("- **PII logging**: PII fields exist. Never log PII values in plaintext");
  }
  if (policies.soft_delete) {
    lines.push("- **Soft delete**: Some relationships use soft_delete cascade. Filter deleted rows");
  }

  // Custom policies
  for (const [key, value] of Object.entries(policies)) {
    if (key === "tenant_isolation" || key === "pii_logging" || key === "soft_delete") continue;
    lines.push(`- **${key}**: ${value ? "enabled" : "disabled"}`);
  }
  lines.push("");
}

function appendVerificationCommands(lines: string[]): void {
  lines.push("## Verification");
  lines.push("");
  lines.push("Run these commands to verify your changes:");
  lines.push("");
  lines.push("```bash");
  lines.push("npx dikta verify      # Validate contracts against schema");
  lines.push("pnpm typecheck        # TypeScript type checking");
  lines.push("pnpm test             # Run test suite");
  lines.push("```");
  lines.push("");
}
