import { describe, it, expect } from "vitest";
import {
  defineEntity,
  createRegistry,
  defineQuery,
  createQueryRegistry,
  uuid,
  string,
  integer,
  timestamp,
  enumField,
  ref,
} from "@dikta/core";
import { generateAgentContext } from "../src/context-generator.js";
import { generateInstructions } from "../src/instructions.js";

function buildContext() {
  const Customer = defineEntity({
    name: "Customer",
    fields: {
      id: uuid({ role: "identifier" }),
      email: string({ pii: true, role: "display_name" }),
      created_at: timestamp(),
    },
    invariants: ["email must be unique"],
  });

  const Order = defineEntity({
    name: "Order",
    fields: {
      id: uuid({ role: "identifier" }),
      customer_id: ref("Customer", { cascade: "soft_delete" }),
      status: enumField(["pending", "paid", "shipped"] as const),
      total: integer({ role: "monetary" }),
    },
  });

  const schema = createRegistry([Customer, Order]);

  const findOrders = defineQuery("findOrders", {
    purpose: "List orders",
    from: "Order",
    params: {
      customer_id: { type: "uuid", required: true },
    },
    returns: {
      shape: {
        id: "uuid",
        status: "string",
        total: "integer",
      },
    },
    performance: {
      max_rows: 100,
      scan_strategy: "index_only",
    },
    security: {
      row_filter: "customer_id",
    },
  });

  const queries = createQueryRegistry([findOrders], schema);
  return generateAgentContext(schema, queries);
}

describe("generateInstructions", () => {
  it("should include entity names", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("Customer");
    expect(md).toContain("Order");
  });

  it("should include entity count", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("**Entities**: 2");
  });

  it("should include relationships table", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("## Relationships");
    expect(md).toContain("| Order | Customer | many_to_one |");
  });

  it("should include PII warning", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("## PII Fields");
    expect(md).toContain("DO NOT LOG");
    expect(md).toContain("`Customer.email`");
  });

  it("should include state machines", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("## State Machines");
    expect(md).toContain("`Order.status`");
  });

  it("should include contracts summary", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("## Query Contracts");
    expect(md).toContain("**Total**: 1");
    expect(md).toContain("Order: 1");
  });

  it("should include policy rules", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("## Policies");
    expect(md).toContain("Tenant isolation");
    expect(md).toContain("PII logging");
    expect(md).toContain("Soft delete");
  });

  it("should include verification commands", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("## Verification");
    expect(md).toContain("npx dikta verify");
    expect(md).toContain("pnpm typecheck");
    expect(md).toContain("pnpm test");
  });

  it("should include auto-generated notice", () => {
    const ctx = buildContext();
    const md = generateInstructions(ctx);

    expect(md).toContain("Auto-generated by `dikta context`");
  });
});
