const HEADER_LINES: readonly string[] = [
  "// ──────────────────────────────────────────────────────────────",
  "// AUTO-GENERATED by @dikta/generator — DO NOT EDIT",
  "// Re-run `dikta generate` to regenerate this file.",
  "// ──────────────────────────────────────────────────────────────",
];

export function fileHeader(sourcePath?: string): string {
  const lines = [...HEADER_LINES];
  if (sourcePath) {
    lines.push(`// Source: ${sourcePath}`);
  }
  return lines.join("\n") + "\n";
}

export function toSnakeCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1_$2")
    .toLowerCase();
}

export function toTableName(name: string): string {
  return toSnakeCase(name);
}

export function toPascalCase(name: string): string {
  return name
    .replace(/(^|[_\s-])([a-z])/g, (_match, _sep, char: string) =>
      char.toUpperCase(),
    )
    .replace(/[_\s-]/g, "");
}

export function toCamelCase(name: string): string {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}
